//dispatchers
export const SET_CURRENT_USER ='SET_CURRENT_USER';
export const GET_ERRORS='GET_ERRORS'; //set errors
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_FOLLOWINGS = "GET_FOLLOWINGS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const ADD_FOLLOWING = "ADD_FOLLOWING";
export const FOLLOWING_LOADING = "FOLLOWING_LOADING";
export const DELETE_FOLLOWING = "DELETE_FOLLOWING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";